name: Update Image Deployment with IMAGE_TAG

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Flask Helm Chart Repo
        uses: actions/checkout@v4
        with:
          repository: github.com/sahil-sharma/k8s-stuff
          path: flask-otel-app-chart

      - name: Update image tag
        run: |
          apt-get update && apt install yq -y
          SHA=${{ github.event.client_payload.sha }}
          yq eval '.image.tag = "v2"' -i flask-otel-app-chart/values.yaml

      - name: Commit and push
        run: |
          cd infra-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add flask-otel-app-chart/values.yaml
          git commit -m "From CI: Update image tag to ${SHA}"
          git push origin main
